export const standingResponse = {
  seasons: [2020, 2019, 2018],
  standing: [
    {
      season: 2020,
      group: 'Group 1',
      rank: 1,
      points: 12,
      form: 'WWDDW',
      goalsDiff: '5',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 3,
        lose: 0,
        goals: {
          for: 7,
          against: 2,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 2,
        lose: 0,
        goals: {
          for: 4,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 3,
          against: 0,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 2,
      points: 11,
      form: 'WWDDL',
      goalsDiff: '3',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 2,
        lose: 1,
        goals: {
          for: 7,
          against: 4,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 4,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 2,
        lose: 0,
        goals: {
          for: 3,
          against: 2,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 3,
      points: 7,
      form: 'LLWDW',
      goalsDiff: '0',
      status: 'same',
      decription: null,
      all: {
        win: 2,
        draw: 1,
        lose: 3,
        goals: {
          for: 6,
          against: 6,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 4,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 0,
        lose: 2,
        goals: {
          for: 2,
          against: 4,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 4,
      points: 2,
      form: 'LLLDL',
      goalsDiff: '-8',
      status: 'same',
      decription: null,
      all: {
        win: 0,
        draw: 2,
        lose: 4,
        goals: {
          for: 3,
          against: 11,
        },
        played: 6,
      },
      home: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 1,
          against: 4,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 2,
          against: 7,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 1,
      points: 15,
      form: 'WWWLW',
      goalsDiff: '10',
      status: 'same',
      decription: null,
      all: {
        win: 5,
        draw: 0,
        lose: 1,
        goals: {
          for: 16,
          against: 6,
        },
        played: 6,
      },
      home: {
        win: 3,
        draw: 0,
        lose: 0,
        goals: {
          for: 11,
          against: 3,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 5,
          against: 3,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 2,
      points: 10,
      form: 'LWWWD',
      goalsDiff: '1',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 1,
        lose: 2,
        goals: {
          for: 8,
          against: 7,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 2,
          against: 3,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 6,
          against: 4,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 3,
      points: 10,
      form: 'WLLWD',
      goalsDiff: '3',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 1,
        lose: 2,
        goals: {
          for: 7,
          against: 4,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 6,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 1,
          against: 2,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 4,
      points: 0,
      form: 'LLLLL',
      goalsDiff: '-14',
      status: 'same',
      decription: null,
      all: {
        win: 0,
        draw: 0,
        lose: 6,
        goals: {
          for: 3,
          against: 17,
        },
        played: 6,
      },
      home: {
        win: 0,
        draw: 0,
        lose: 3,
        goals: {
          for: 1,
          against: 6,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 0,
        lose: 3,
        goals: {
          for: 2,
          against: 11,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 1,
      points: 16,
      form: 'WWWDW',
      goalsDiff: '7',
      status: 'same',
      decription: null,
      all: {
        win: 5,
        draw: 1,
        lose: 0,
        goals: {
          for: 12,
          against: 5,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 8,
          against: 4,
        },
        played: 3,
      },
      away: {
        win: 3,
        draw: 0,
        lose: 0,
        goals: {
          for: 4,
          against: 1,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 2,
      points: 13,
      form: 'WLWDW',
      goalsDiff: '8',
      status: 'same',
      decription: null,
      all: {
        win: 4,
        draw: 1,
        lose: 1,
        goals: {
          for: 12,
          against: 4,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 7,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 5,
          against: 2,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 3,
      points: 3,
      form: 'LLLWL',
      goalsDiff: '-7',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 0,
        lose: 5,
        goals: {
          for: 9,
          against: 16,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 0,
        lose: 2,
        goals: {
          for: 5,
          against: 6,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 0,
        lose: 3,
        goals: {
          for: 4,
          against: 10,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 4,
      points: 3,
      form: 'LWLLL',
      goalsDiff: '-8',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 0,
        lose: 5,
        goals: {
          for: 5,
          against: 13,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 0,
        lose: 2,
        goals: {
          for: 2,
          against: 4,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 0,
        lose: 3,
        goals: {
          for: 3,
          against: 9,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 1,
      points: 11,
      form: 'WDLWW',
      goalsDiff: '10',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 2,
        lose: 1,
        goals: {
          for: 13,
          against: 3,
        },
        played: 6,
      },
      home: {
        win: 3,
        draw: 0,
        lose: 0,
        goals: {
          for: 11,
          against: 0,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 2,
        lose: 1,
        goals: {
          for: 2,
          against: 3,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 2,
      points: 9,
      form: 'LWDWD',
      goalsDiff: '-3',
      status: 'same',
      decription: null,
      all: {
        win: 2,
        draw: 3,
        lose: 1,
        goals: {
          for: 10,
          against: 13,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 2,
        lose: 0,
        goals: {
          for: 7,
          against: 5,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 3,
          against: 8,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 3,
      points: 6,
      form: 'WDDLD',
      goalsDiff: '1',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 3,
        lose: 2,
        goals: {
          for: 9,
          against: 8,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 2,
        lose: 0,
        goals: {
          for: 5,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 4,
          against: 6,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 4,
      points: 6,
      form: 'LLWLL',
      goalsDiff: '-8',
      status: 'same',
      decription: null,
      all: {
        win: 2,
        draw: 0,
        lose: 4,
        goals: {
          for: 5,
          against: 13,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 4,
          against: 3,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 0,
        lose: 3,
        goals: {
          for: 1,
          against: 10,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 1,
      points: 13,
      form: 'DWWWL',
      goalsDiff: '3',
      status: 'same',
      decription: null,
      all: {
        win: 4,
        draw: 1,
        lose: 1,
        goals: {
          for: 9,
          against: 6,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 5,
          against: 5,
        },
        played: 3,
      },
      away: {
        win: 3,
        draw: 0,
        lose: 0,
        goals: {
          for: 4,
          against: 1,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 2,
      points: 10,
      form: 'DLWWW',
      goalsDiff: '5',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 1,
        lose: 2,
        goals: {
          for: 12,
          against: 7,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 6,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 6,
          against: 5,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 3,
      points: 8,
      form: 'DWLLW',
      goalsDiff: '-1',
      status: 'same',
      decription: null,
      all: {
        win: 2,
        draw: 2,
        lose: 2,
        goals: {
          for: 8,
          against: 9,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 4,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 4,
          against: 7,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 4,
      points: 2,
      form: 'DLLLL',
      goalsDiff: '-7',
      status: 'same',
      decription: null,
      all: {
        win: 0,
        draw: 2,
        lose: 4,
        goals: {
          for: 4,
          against: 11,
        },
        played: 6,
      },
      home: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 2,
          against: 7,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 2,
          against: 4,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 1,
      points: 12,
      form: 'WWLWL',
      goalsDiff: '4',
      status: 'same',
      decription: null,
      all: {
        win: 4,
        draw: 0,
        lose: 2,
        goals: {
          for: 9,
          against: 5,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 4,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 5,
          against: 3,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 2,
      points: 10,
      form: 'LLWWW',
      goalsDiff: '1',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 1,
        lose: 2,
        goals: {
          for: 5,
          against: 4,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 3,
          against: 1,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 0,
        lose: 2,
        goals: {
          for: 2,
          against: 3,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 3,
      points: 8,
      form: 'WLWLD',
      goalsDiff: '0',
      status: 'same',
      decription: null,
      all: {
        win: 2,
        draw: 2,
        lose: 2,
        goals: {
          for: 7,
          against: 7,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 3,
          against: 3,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 4,
          against: 4,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 4,
      points: 4,
      form: 'LWLLD',
      goalsDiff: '-5',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 1,
        lose: 4,
        goals: {
          for: 5,
          against: 10,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 0,
        lose: 2,
        goals: {
          for: 4,
          against: 6,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 1,
          against: 4,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 1,
      points: 11,
      form: 'WDDWL',
      goalsDiff: '3',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 2,
        lose: 1,
        goals: {
          for: 7,
          against: 4,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 5,
          against: 4,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 2,
          against: 0,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 2,
      points: 8,
      form: 'LLDDW',
      goalsDiff: '-3',
      status: 'same',
      decription: null,
      all: {
        win: 2,
        draw: 2,
        lose: 2,
        goals: {
          for: 9,
          against: 12,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 2,
        lose: 0,
        goals: {
          for: 4,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 0,
        lose: 2,
        goals: {
          for: 5,
          against: 10,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 3,
      points: 6,
      form: 'WDDLD',
      goalsDiff: '2',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 3,
        lose: 2,
        goals: {
          for: 9,
          against: 7,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 5,
          against: 1,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 2,
        lose: 1,
        goals: {
          for: 4,
          against: 6,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 4,
      points: 6,
      form: 'LWDDD',
      goalsDiff: '-2',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 3,
        lose: 2,
        goals: {
          for: 6,
          against: 8,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 5,
          against: 5,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 2,
        lose: 1,
        goals: {
          for: 1,
          against: 3,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 1,
      points: 16,
      form: 'WWWDW',
      goalsDiff: '6',
      status: 'same',
      decription: null,
      all: {
        win: 5,
        draw: 1,
        lose: 0,
        goals: {
          for: 7,
          against: 1,
        },
        played: 6,
      },
      home: {
        win: 3,
        draw: 0,
        lose: 0,
        goals: {
          for: 5,
          against: 1,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 2,
          against: 0,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 2,
      points: 12,
      form: 'LWWWW',
      goalsDiff: '2',
      status: 'same',
      decription: null,
      all: {
        win: 4,
        draw: 0,
        lose: 2,
        goals: {
          for: 7,
          against: 5,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 3,
          against: 1,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 4,
          against: 4,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 3,
      points: 3,
      form: 'DLLDL',
      goalsDiff: '-3',
      status: 'same',
      decription: null,
      all: {
        win: 0,
        draw: 3,
        lose: 3,
        goals: {
          for: 1,
          against: 4,
        },
        played: 6,
      },
      home: {
        win: 0,
        draw: 2,
        lose: 1,
        goals: {
          for: 0,
          against: 1,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 1,
          against: 3,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 4,
      points: 2,
      form: 'DLLLL',
      goalsDiff: '-5',
      status: 'same',
      decription: null,
      all: {
        win: 0,
        draw: 2,
        lose: 4,
        goals: {
          for: 2,
          against: 7,
        },
        played: 6,
      },
      home: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 2,
          against: 4,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 0,
          against: 3,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 1,
      points: 13,
      form: 'WDLWW',
      goalsDiff: '8',
      status: 'same',
      decription: null,
      all: {
        win: 4,
        draw: 1,
        lose: 1,
        goals: {
          for: 10,
          against: 2,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 7,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 3,
          against: 0,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 2,
      points: 10,
      form: 'DLWWL',
      goalsDiff: '2',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 1,
        lose: 2,
        goals: {
          for: 7,
          against: 5,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 2,
          against: 1,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 5,
          against: 4,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 3,
      points: 6,
      form: 'DDDLW',
      goalsDiff: '-2',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 3,
        lose: 2,
        goals: {
          for: 2,
          against: 4,
        },
        played: 6,
      },
      home: {
        win: 0,
        draw: 2,
        lose: 1,
        goals: {
          for: 1,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 1,
          against: 2,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 4,
      points: 4,
      form: 'LWDLL',
      goalsDiff: '-8',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 1,
        lose: 4,
        goals: {
          for: 2,
          against: 10,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 0,
        lose: 2,
        goals: {
          for: 2,
          against: 4,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 0,
          against: 6,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 1,
      points: 11,
      form: 'WWDDW',
      goalsDiff: '3',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 2,
        lose: 1,
        goals: {
          for: 9,
          against: 6,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 5,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 4,
          against: 4,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 2,
      points: 9,
      form: 'LWDDD',
      goalsDiff: '1',
      status: 'same',
      decription: null,
      all: {
        win: 2,
        draw: 3,
        lose: 1,
        goals: {
          for: 9,
          against: 8,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 5,
          against: 3,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 2,
        lose: 1,
        goals: {
          for: 4,
          against: 5,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 3,
      points: 7,
      form: 'DLDDD',
      goalsDiff: '0',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 4,
        lose: 1,
        goals: {
          for: 6,
          against: 6,
        },
        played: 6,
      },
      home: {
        win: 0,
        draw: 2,
        lose: 1,
        goals: {
          for: 2,
          against: 3,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 2,
        lose: 0,
        goals: {
          for: 4,
          against: 3,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 4,
      points: 3,
      form: 'DLDDL',
      goalsDiff: '-4',
      status: 'same',
      decription: null,
      all: {
        win: 0,
        draw: 3,
        lose: 3,
        goals: {
          for: 5,
          against: 9,
        },
        played: 6,
      },
      home: {
        win: 0,
        draw: 2,
        lose: 1,
        goals: {
          for: 4,
          against: 5,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 1,
          against: 4,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 1,
      points: 14,
      form: 'DWWWW',
      goalsDiff: '7',
      status: 'same',
      decription: null,
      all: {
        win: 4,
        draw: 2,
        lose: 0,
        goals: {
          for: 8,
          against: 1,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 3,
          against: 1,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 5,
          against: 0,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 2,
      points: 12,
      form: 'DWDWW',
      goalsDiff: '5',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 3,
        lose: 0,
        goals: {
          for: 6,
          against: 1,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 2,
        lose: 0,
        goals: {
          for: 2,
          against: 0,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 4,
          against: 1,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 3,
      points: 5,
      form: 'WLDLL',
      goalsDiff: '-2',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 2,
        lose: 3,
        goals: {
          for: 4,
          against: 6,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 0,
        lose: 2,
        goals: {
          for: 2,
          against: 3,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 2,
        lose: 1,
        goals: {
          for: 2,
          against: 3,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 3',
      rank: 4,
      points: 1,
      form: 'LLLLL',
      goalsDiff: '-10',
      status: 'same',
      decription: null,
      all: {
        win: 0,
        draw: 1,
        lose: 5,
        goals: {
          for: 1,
          against: 11,
        },
        played: 6,
      },
      home: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 1,
          against: 7,
        },
        played: 3,
      },
      away: {
        win: 0,
        draw: 0,
        lose: 3,
        goals: {
          for: 0,
          against: 4,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 1,
      points: 11,
      form: 'WWDDL',
      goalsDiff: '4',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 2,
        lose: 1,
        goals: {
          for: 8,
          against: 4,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 6,
          against: 4,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 2,
        lose: 0,
        goals: {
          for: 2,
          against: 0,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 2,
      points: 10,
      form: 'LWWDW',
      goalsDiff: '2',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 1,
        lose: 2,
        goals: {
          for: 10,
          against: 8,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 4,
          against: 2,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 6,
          against: 6,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 3,
      points: 8,
      form: 'WLDDW',
      goalsDiff: '-2',
      status: 'same',
      decription: null,
      all: {
        win: 2,
        draw: 2,
        lose: 2,
        goals: {
          for: 5,
          against: 7,
        },
        played: 6,
      },
      home: {
        win: 0,
        draw: 2,
        lose: 1,
        goals: {
          for: 2,
          against: 4,
        },
        played: 3,
      },
      away: {
        win: 2,
        draw: 0,
        lose: 1,
        goals: {
          for: 3,
          against: 3,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 4',
      rank: 4,
      points: 4,
      form: 'LLLDL',
      goalsDiff: '-4',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 1,
        lose: 4,
        goals: {
          for: 5,
          against: 9,
        },
        played: 6,
      },
      home: {
        win: 0,
        draw: 1,
        lose: 2,
        goals: {
          for: 2,
          against: 4,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 0,
        lose: 2,
        goals: {
          for: 3,
          against: 5,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 1,
      points: 12,
      form: 'DDWDW',
      goalsDiff: '4',
      status: 'same',
      decription: null,
      all: {
        win: 3,
        draw: 3,
        lose: 0,
        goals: {
          for: 9,
          against: 5,
        },
        played: 6,
      },
      home: {
        win: 2,
        draw: 1,
        lose: 0,
        goals: {
          for: 6,
          against: 3,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 2,
        lose: 0,
        goals: {
          for: 3,
          against: 2,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 1',
      rank: 2,
      points: 9,
      form: 'DWWDD',
      goalsDiff: '2',
      status: 'same',
      decription: null,
      all: {
        win: 2,
        draw: 3,
        lose: 1,
        goals: {
          for: 8,
          against: 6,
        },
        played: 6,
      },
      home: {
        win: 1,
        draw: 2,
        lose: 0,
        goals: {
          for: 5,
          against: 3,
        },
        played: 3,
      },
      away: {
        win: 1,
        draw: 1,
        lose: 1,
        goals: {
          for: 3,
          against: 3,
        },
        played: 3,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 1,
      points: 8,
      form: 'DDWW',
      goalsDiff: '2',
      status: 'same',
      decription: null,
      all: {
        win: 2,
        draw: 2,
        lose: 0,
        goals: {
          for: 3,
          against: 1,
        },
        played: 4,
      },
      home: {
        win: 1,
        draw: 1,
        lose: 0,
        goals: {
          for: 2,
          against: 1,
        },
        played: 2,
      },
      away: {
        win: 1,
        draw: 1,
        lose: 0,
        goals: {
          for: 1,
          against: 0,
        },
        played: 2,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 2,
      points: 5,
      form: 'DDLW',
      goalsDiff: '1',
      status: 'same',
      decription: null,
      all: {
        win: 1,
        draw: 2,
        lose: 1,
        goals: {
          for: 3,
          against: 2,
        },
        played: 4,
      },
      home: {
        win: 0,
        draw: 1,
        lose: 1,
        goals: {
          for: 0,
          against: 1,
        },
        played: 2,
      },
      away: {
        win: 1,
        draw: 1,
        lose: 0,
        goals: {
          for: 3,
          against: 1,
        },
        played: 2,
      },
    },
    {
      season: 2020,
      group: 'Group 2',
      rank: 3,
      points: 2,
      form: 'DDLL',
      goalsDiff: '-3',
      status: 'same',
      decription: null,
      all: {
        win: 0,
        draw: 2,
        lose: 2,
        goals: {
          for: 0,
          against: 3,
        },
        played: 4,
      },
      home: {
        win: 0,
        draw: 1,
        lose: 1,
        goals: {
          for: 0,
          against: 2,
        },
        played: 2,
      },
      away: {
        win: 0,
        draw: 1,
        lose: 1,
        goals: {
          for: 0,
          against: 1,
        },
        played: 2,
      },
    },
  ],
};
