const routesPath = {
  HOME: '/sport/:sport',
  REGISTER: '/register',
  BETTING: '/bet/sport/:sport',
  WIDGETS: '/widgets',
  BETTING_DETAILS: '/bet/:sport/:league',
  USER_PROFILE: '/user/profile',
  LEAGUE_TABLE: '/league-table',
  LIVE_SCORES: '/live-scores/sport/:sport',
  LIVE_BETS: '/live-bets/:sport/:sport',
  BOOK_MARKERS: '/bookmakers',
  NOT_FOUND: '/page-not-found',
  TIPS: '/tip',
  BOOK_MARKERS_DETAILS: '/bookmakers/:id',
  BETTING_TOOLS_DASHBOARD: '/betting-tools-dashboard',
  ADMIN_HOME: '/admin/dashboard',
  ADMIN_LANGUAGE: '/admin/manage-language',
  ADMIN_HEADLINES: '/admin/headlines',
  ADMIN_BOOKMAKERS: '/admin/bookmakers',
  ADMIN_AUTH: '/admin/login-odds-bug',
  ADMIN_CONTENT: '/admin/content-management',
  ADMIN_SITEMAP: '/admin/settings/site-map',
  ADMIN_ADD_BOOKMAKERS: '/admin/bookmakers-list',
  ADMIN_BANNERS: '/admin/banners',
  BETTING_TOOLS_TYPES: '/betting-tools-dashboard/:type',
  FAQ: '/faq',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS_CONDITIONS: '/terms-conditions',
  USER_SETTINGS: '/admin/user-settings',
  SITE_SETTINGS: '/admin/site-settings',
};

export default routesPath;
