/* eslint-disable react/display-name */
import { lazy } from 'react';
import { Redirect } from 'react-router-dom';
import AdminLayouts from '../layouts/admin-layouts';
import Layouts from '../layouts/Layouts';
import NoWrapper from '../layouts/NoWrapper';
import Home from '../pages/home/Home';

import { IRoutes } from './@types/type';
import routesPath from './path.routes';

export const publicRoutes: IRoutes[] = [
  {
    title: 'home',
    path: '/',
    isPublic: true,
    layout: Layouts,
    navLowerLayer: true,
    component: () => <Redirect to="/sport/soccer" />,
  },
  {
    title: '',
    path: routesPath.HOME,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: true,
    component: () => <Home />,
  },

  {
    title: 'bet',
    path: routesPath.BETTING,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: true,
    component: lazy(() => import('../pages/betting/v2betting-view')),
  },
  {
    title: 'Widgets',
    path: routesPath.WIDGETS,
    isPublic: true,
    layout: NoWrapper,
    navLowerLayer: false,
    component: lazy(() => import('../pages/widget-home/widgets-home')),
  },
  {
    title: 'bettings-details',
    path: routesPath.BETTING_DETAILS,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/betting-details/bettings-details')),
  },
  {
    title: 'league-table',
    path: routesPath.LEAGUE_TABLE,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/league-team-table/League-team-table')),
  },
  {
    title: 'live-scores',
    path: routesPath.LIVE_SCORES,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: true,
    component: lazy(() => import('../pages/live-scores/live-scores')),
  },
  {
    title: 'betting-tools-dashboard',
    path: routesPath.BETTING_TOOLS_DASHBOARD,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: true,
    component: lazy(() => import('../pages/betting-tools-dashboard/betting-tools-dashboard')),
  },
  {
    title: 'bookmarkers',
    path: routesPath.BOOK_MARKERS,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/bookmarkers/bookmarkers')),
  },
  {
    title: 'bookmarkers',
    path: routesPath.BOOK_MARKERS_DETAILS,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/bookmarkers/bookmarkers-details')),
  },
  {
    title: 'bookmaker-tools-type',
    path: routesPath.BETTING_TOOLS_TYPES,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: true,
    component: lazy(() => import('../pages/betting-tools-dashboard/bettings-tools-type')),
  },
  {
    title: 'user-profile',
    path: routesPath.USER_PROFILE,
    isPublic: false,
    layout: Layouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/user-profile/user-profile')),
  },
  {
    title: 'live-bets',
    path: routesPath.LIVE_BETS,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: true,
    component: lazy(() => import('../pages/betting/live-bets')),
  },
  {
    title: 'faq',
    path: routesPath.FAQ,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/faq/faq')),
  },
  {
    title: 'privacy-policy',
    path: routesPath.PRIVACY_POLICY,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/privacy-policy/privacy-policy')),
  },
  {
    title: 'terms-conditions',
    path: routesPath.TERMS_CONDITIONS,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/terms-conditions/terms-conditions')),
  },
  {
    title: 'tips',
    path: routesPath.TIPS,
    isPublic: true,
    layout: Layouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/tips/tips')),
  },
  // Admin Routes
  {
    title: 'admin-bookmakers',
    path: routesPath.ADMIN_BOOKMAKERS,
    isPublic: false,
    layout: AdminLayouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/admin/bookmarker/bookmarker')),
  },
  {
    title: 'admin-auth',
    path: routesPath.ADMIN_AUTH,
    isPublic: true,
    layout: AdminLayouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/admin/auth/admin-login')),
  },
  {
    title: 'admin-site-map',
    path: routesPath.ADMIN_SITEMAP,
    isPublic: false,
    layout: AdminLayouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/admin/site-map/site-map-view')),
  },
  {
    title: 'admin-home',
    path: routesPath.ADMIN_HOME,
    isPublic: false,
    layout: AdminLayouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/admin/dashboard/Overview')),
  },
  {
    title: 'admin-bookmakers',
    path: routesPath.ADMIN_ADD_BOOKMAKERS,
    isPublic: false,
    layout: AdminLayouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/admin/bookmarker/components/whitelisted-bookmarker')),
  },
  {
    title: 'admin-web contents',
    path: routesPath.ADMIN_CONTENT,
    isPublic: false,
    layout: AdminLayouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/admin/web-contents/web-contents')),
  },
  {
    title: 'admin-headlines',
    path: routesPath.ADMIN_HEADLINES,
    isPublic: false,
    layout: AdminLayouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/admin/web-contents/components/headlines/headline')),
  },
  {
    title: 'user-settings',
    path: routesPath.USER_SETTINGS,
    isPublic: false,
    layout: AdminLayouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/admin/user-settings/user-settings')),
  },
  {
    title: 'admin-banners',
    path: routesPath.ADMIN_BANNERS,
    isPublic: false,
    layout: AdminLayouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/admin/banners/banners')),
  },
  {
    title: 'user-settings',
    path: routesPath.SITE_SETTINGS,
    isPublic: false,
    layout: AdminLayouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/admin/site-settings')),
  },
  {
    title: 'manage-language',
    path: routesPath.ADMIN_LANGUAGE,
    isPublic: false,
    layout: AdminLayouts,
    navLowerLayer: false,
    component: lazy(() => import('../pages/admin/manage-languages/manage-language')),
  },
];
